// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-of7l0GRmClUZciR1Ak8GgBJIpmKLHY0',
    appId: '1:1035354071090:android:5ff716721e08502f791c2b',
    messagingSenderId: '1035354071090',
    projectId: 'bright-feat-372314',
    storageBucket: 'bright-feat-372314.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATbJfi-frLrNubF-qUWalhD1jmiUAv8nY',
    appId: '1:1035354071090:ios:b604a290a6c2f5b1791c2b',
    messagingSenderId: '1035354071090',
    projectId: 'bright-feat-372314',
    storageBucket: 'bright-feat-372314.appspot.com',
    iosClientId:
        '1035354071090-5lu5cpun669akd6r5tq514fqjmm837sr.apps.googleusercontent.com',
    iosBundleId: 'com.example.beefit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATbJfi-frLrNubF-qUWalhD1jmiUAv8nY',
    appId: '1:1035354071090:ios:b604a290a6c2f5b1791c2b',
    messagingSenderId: '1035354071090',
    projectId: 'bright-feat-372314',
    storageBucket: 'bright-feat-372314.appspot.com',
    iosClientId:
        '1035354071090-5lu5cpun669akd6r5tq514fqjmm837sr.apps.googleusercontent.com',
    iosBundleId: 'com.example.beefit',
  );
}
